# Generated by Django 5.2.3 on 2025-06-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="senalTenica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activo",
                    models.CharField(
                        choices=[
                            ("AAPL", "Apple"),
                            ("TSLA", "Tesla"),
                            ("BTC-USD", "Bitcoin"),
                            ("ETH-USD", "Ethereum"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=10
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("indicador", models.CharField(max_length=50)),
                ("valor", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Senal tecnica",
                "verbose_name_plural": "Senales tecnicas",
            },
        ),
    ]
