# Generated by Django 5.2.3 on 2025-06-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="senalTenica",
            new_name="senalTecnica",
        ),
    ]
