# Generated by Django 5.2.3 on 2025-07-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0002_rename_senaltenica_senaltecnica"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtributoDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("activo", models.CharField(max_length=70)),
                ("precio", models.FloatField(blank=True, null=True)),
                ("macd", models.CharField(max_length=10)),
                ("pmm5", models.CharField(max_length=10)),
                ("pmm10", models.CharField(max_length=10)),
                ("pmm20", models.CharField(max_length=10)),
                ("pmm30", models.CharField(max_length=10)),
                ("mm5_10", models.CharField(max_length=10)),
                ("mm10_20", models.CharField(max_length=10)),
                ("tripleCruce", models.CharField(max_length=10)),
                ("pmm100", models.CharField(max_length=10)),
                ("rsi", models.CharField(max_length=10)),
                ("dmi", models.CharField(max_length=10)),
                ("adx", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Atributos de activo",
                "verbose_name_plural": "Conjunto de atributos de activo",
            },
        ),
        migrations.AlterField(
            model_name="senaltecnica",
            name="activo",
            field=models.CharField(max_length=20),
        ),
    ]
