# Generated by Django 5.2.3 on 2025-07-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0003_atributodashboard_alter_senaltecnica_activo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AtributoDashboard",
        ),
    ]
