# Generated by Django 5.2.3 on 2025-07-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0004_delete_atributodashboard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="senaltecnica",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Senal tecnica",
                "verbose_name_plural": "Senales tecnicas",
            },
        ),
        migrations.AddField(
            model_name="senaltecnica",
            name="detalle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
