# Generated by Django 5.2.3 on 2025-07-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0005_alter_senaltecnica_options_senaltecnica_detalle"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="senaltecnica",
            unique_together={("activo", "indicador")},
        ),
    ]
