# Generated by Django 5.2.3 on 2025-07-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0006_alter_senaltecnica_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senaltecnica",
            name="fecha",
            field=models.DateTimeField(),
        ),
    ]
