# Generated by Django 5.2.3 on 2025-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0007_alter_senaltecnica_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="senaltecnica",
            name="rendimiento",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
