# Generated by Django 5.2.3 on 2025-07-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0008_senaltecnica_rendimiento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="senaltecnica",
            old_name="valor",
            new_name="precio_actual",
        ),
        migrations.AddField(
            model_name="senaltecnica",
            name="precio_senal",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
