# Generated by Django 5.2.3 on 2025-09-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0009_rename_valor_senaltecnica_precio_actual_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="senaltecnica",
            options={"ordering": ["-fecha"]},
        ),
        migrations.AlterUniqueTogether(
            name="senaltecnica",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="senaltecnica",
            name="activo",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="senaltecnica",
            name="fecha",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="senaltecnica",
            name="indicador",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="senaltecnica",
            constraint=models.UniqueConstraint(
                fields=("activo", "indicador", "tipo", "fecha"),
                name="uniq_signal_activo_indicador_tipo_fecha",
            ),
        ),
    ]
