# Generated by Django 5.2.3 on 2025-09-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0010_alter_senaltecnica_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="senaltecnica",
            name="uniq_signal_activo_indicador_tipo_fecha",
        ),
        migrations.AddField(
            model_name="senaltecnica",
            name="timeframe",
            field=models.CharField(
                choices=[("D", "daily"), ("W", "weekly")],
                db_index=True,
                default="D",
                max_length=1,
            ),
        ),
        migrations.AddConstraint(
            model_name="senaltecnica",
            constraint=models.UniqueConstraint(
                fields=("activo", "timeframe", "indicador", "tipo", "fecha"),
                name="uniq_signal_activo_tf_indicador_tipo_fecha",
            ),
        ),
    ]
