# Generated by Django 5.2.3 on 2025-09-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "senales",
            "0011_remove_senaltecnica_uniq_signal_activo_indicador_tipo_fecha_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="senaltecnica",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Señal técnica",
                "verbose_name_plural": "Señales técnicas",
            },
        ),
        migrations.AddIndex(
            model_name="senaltecnica",
            index=models.Index(
                fields=["activo", "timeframe", "fecha"], name="signals_idx"
            ),
        ),
    ]
