# Generated by Django 5.2.3 on 2025-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0012_alter_senaltecnica_options_senaltecnica_signals_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senaltecnica",
            name="activo",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
