# Generated by Django 5.2.3 on 2025-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senales", "0013_alter_senaltecnica_activo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senaltecnica",
            name="timeframe",
            field=models.CharField(
                choices=[("D", "daily"), ("W", "weekly")],
                db_index=True,
                default="D",
                max_length=10,
            ),
        ),
    ]
