# Generated by Django 5.2.3 on 2025-09-07 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=16, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriceDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open", models.DecimalField(decimal_places=6, max_digits=16)),
                ("high", models.DecimalField(decimal_places=6, max_digits=16)),
                ("low", models.DecimalField(decimal_places=6, max_digits=16)),
                ("close", models.DecimalField(decimal_places=6, max_digits=16)),
                ("adj_close", models.DecimalField(decimal_places=6, max_digits=16)),
                ("volume", models.BigIntegerField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices_daily",
                        to="market.ticker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "-date"],
                        name="market_pric_ticker__46fa0c_idx",
                    ),
                    models.Index(fields=["-date"], name="market_pric_date_1a4871_idx"),
                ],
                "unique_together": {("ticker", "date")},
            },
        ),
    ]
