# Generated by Django 5.2.3 on 2025-07-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_atributodashboard_adx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atributodashboard",
            name="activo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
