# Generated by Django 5.2.3 on 2025-09-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_favorite_uniq_user_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="atributodashboard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="atributodashboard",
            name="ticker",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
