# Generated by Django 5.2.3 on 2025-09-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_atributodashboard_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atributodashboard",
            name="timeframe",
            field=models.CharField(
                choices=[("D", "daily"), ("W", "weekly")],
                db_index=True,
                default="D",
                max_length=1,
            ),
        ),
        migrations.AddIndex(
            model_name="atributodashboard",
            index=models.Index(
                fields=["ticker", "timeframe"], name="dashboard_a_ticker_879856_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="atributodashboard",
            constraint=models.UniqueConstraint(
                fields=("ticker", "timeframe"), name="uniq_dash_ticker_tf"
            ),
        ),
    ]
