# Generated by Django 5.2.3 on 2025-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_atributodashboard_timeframe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atributodashboard",
            name="ticker",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="ticker",
            field=models.CharField(max_length=32),
        ),
    ]
