# Generated by Django 5.2.3 on 2025-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_atributodashboard_ticker_alter_favorite_ticker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atributodashboard",
            name="activo",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="atributodashboard",
            name="ticker",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="ticker",
            field=models.CharField(max_length=50),
        ),
    ]
