# Generated by Django 5.2.3 on 2025-07-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReporteTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("activo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "timeframe",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("precio", models.FloatField(blank=True, null=True)),
                ("macd", models.CharField(blank=True, max_length=10, null=True)),
                ("pmm5", models.CharField(blank=True, max_length=10, null=True)),
                ("pmm10", models.CharField(blank=True, max_length=10, null=True)),
                ("pmm20", models.CharField(blank=True, max_length=10, null=True)),
                ("pmm30", models.CharField(blank=True, max_length=10, null=True)),
                ("mm5_10", models.CharField(blank=True, max_length=10, null=True)),
                ("mm10_20", models.CharField(blank=True, max_length=10, null=True)),
                ("tripleCruce", models.CharField(blank=True, max_length=10, null=True)),
                ("pmm100", models.CharField(blank=True, max_length=10, null=True)),
                ("rsi", models.CharField(blank=True, max_length=10, null=True)),
                ("dmi", models.CharField(blank=True, max_length=10, null=True)),
                ("adx", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Reporte tecnico",
                "verbose_name_plural": "Reportes tecnicos",
            },
        ),
    ]
