# Generated by Django 5.2.3 on 2025-09-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activo", "0001_initial"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("country", models.CharField(blank=True, default="", max_length=64)),
                ("exchange", models.CharField(blank=True, default="", max_length=64)),
                ("currency", models.CharField(blank=True, default="", max_length=16)),
                ("sector", models.CharField(blank=True, default="", max_length=64)),
                ("industry", models.CharField(blank=True, default="", max_length=128)),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "shares_outstanding",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="market.ticker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sector"], name="activo_comp_sector_c28a02_idx"
                    ),
                    models.Index(
                        fields=["industry"], name="activo_comp_industr_72eaec_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComparablePeer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField(default=0)),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peers_base",
                        to="market.ticker",
                    ),
                ),
                (
                    "peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peers_of",
                        to="market.ticker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["base", "rank"], name="activo_comp_base_id_834d16_idx"
                    )
                ],
                "unique_together": {("base", "peer")},
            },
        ),
        migrations.CreateModel(
            name="FundamentalMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("eps", "EPS"),
                            ("fcfMargin", "FCF Margin"),
                            ("grossMargin", "Gross Margin"),
                            ("totalDebtToTotalAsset", "Debt/Assets"),
                            ("netMargin", "Net Margin"),
                            ("operatingMargin", "Operating Margin"),
                            ("peTTM", "P/E TTM"),
                            ("roaTTM", "ROA TTM"),
                            ("roeTTM", "ROE TTM"),
                            ("roicTTM", "ROIC TTM"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("period_end", models.DateField(db_index=True)),
                ("value", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundamentals",
                        to="market.ticker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "metric"],
                        name="activo_fund_ticker__497cbc_idx",
                    ),
                    models.Index(
                        fields=["metric", "-period_end"],
                        name="activo_fund_metric_71b330_idx",
                    ),
                ],
                "unique_together": {("ticker", "metric", "period_end")},
            },
        ),
    ]
