# Generated by Django 5.2.3 on 2025-09-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activo", "0002_companyprofile_comparablepeer_fundamentalmetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="logo",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="weburl",
            field=models.URLField(blank=True, default=""),
        ),
    ]
