# Generated by Django 5.2.3 on 2025-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activo", "0003_companyprofile_logo_companyprofile_weburl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportetecnico",
            name="activo",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="reportetecnico",
            name="timeframe",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly")],
                default="daily",
                max_length=40,
            ),
        ),
    ]
