# Generated by Django 5.2.3 on 2025-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activo", "0004_alter_reportetecnico_activo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportetecnico",
            name="timeframe",
            field=models.CharField(
                choices=[("D", "Daily"), ("W", "Weekly")],
                db_index=True,
                default="D",
                max_length=1,
            ),
        ),
    ]
