# Generated by Django 5.2.3 on 2025-09-23 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeframe", models.CharField(max_length=8)),
                ("model_name", models.CharField(max_length=32)),
                ("train_end", models.DateField()),
                ("horizon", models.PositiveIntegerField()),
                ("yhat", models.JSONField(default=list)),
                ("metrics", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "model_version",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.ticker"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "timeframe", "model_name", "-train_end"],
                        name="forecasting_ticker__b9386b_idx",
                    )
                ],
                "unique_together": {
                    ("ticker", "timeframe", "model_name", "train_end", "horizon")
                },
            },
        ),
    ]
